name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  # Upload the CLI binaries
  build-cli:
    name: Build CLI (${{ matrix.os-name }}-${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            os-name: linux
            arch: x86_64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            os-name: linux
            arch: aarch64
          - os: macos-latest
            target: x86_64-apple-darwin
            os-name: macos
            arch: x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            os-name: macos
            arch: aarch64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            os-name: windows
            arch: x86_64
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            os-name: windows
            arch: aarch64
    steps:
      - uses: actions/checkout@v6

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        shell: bash

      - name: Update Cargo.toml version
        run: |
          sed -i.bak "s/^version = .*/version = \"${{ env.VERSION }}\"/" abserde-cli/Cargo.toml
        shell: bash

      # Install cross-compilation tools for Linux Aarch64 if needed
      - name: Install ARM target tools
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - uses: swatinem/rust-cache@v2
        with:
          workspaces: "abserde-cli"

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }} -p abserde
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc

      - name: Package artifact (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          cd target/${{ matrix.target}}/release
          zip -j ../../../abserde-${{ env.VERSION }}-${{ matrix.os-name }}-${{ matrix.arch }}.zip abserde

      - name: Package artifact (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          7z a ../../../abserde-${{ env.VERSION }}-${{ matrix.os-name }}-${{ matrix.arch }}.zip abserde.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cli-${{ matrix.os-name }}-${{ matrix.arch }}
          path: abserde-*.zip
  # TODO: Build and upload the library
  build-lib:
    name: Build library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup RoKit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Setup Pesde
        uses: ewd3v/setup-pesde@v0.1.1
        with:
          pesde_token: "${{ github.token }}"

      - name: Build
        run: rojo build default.project.json -o Abserde.rbxm

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Abserde
          path: Abserde.rbxm
  # Publish
  publish:
    name: Publish
    needs: [build-cli, build-lib]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main

      - name: Extract version from tag
        id: get_version
        run: |
          tag=${{ github.ref_name }}
          echo "version=${tag#"v"}" >> "$GITHUB_OUTPUT"

      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@v3
        with:
          tag: ${{ github.ref_name }}

      - name: Bump pesde.toml version
        uses: DervexDev/file-version-bumper@v1
        with:
          path: ./pesde.toml
          version: ${{ steps.get_version.outputs.version }}

      - name: Bump Cargo.toml version
        run: |
          sed -i.bak "s/^version = .*/version = \"${{ steps.get_version.outputs.version }}\"/" abserde-cli/Cargo.toml
        shell: bash

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "release: ${{ github.ref_name }}"
          default_author: github_actions
          tag: ${{ github.ref_name }} --force
          tag_push: --force

      - name: Setup pesde
        uses: ewd3v/setup-pesde@v0.1.1
        with:
          pesde_token: "${{ secrets.PESDE_TOKEN || github.token }}"

      - name: Publish to Pesde
        run: pesde publish -y

      - name: Read changelog
        id: read_changelog
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.get_version.outputs.version }}

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: assets
          merge-multiple: true

      - name: Generate checksums
        run: |
          cd assets
          sha256sum * > checksums.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            # Changelog
            ${{ steps.read_changelog.outputs.changes }}

          files: |
            assets/*
          generate_release_notes: true
